name: flutter_sleep_sounds
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-197.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.3
  http: ^1.1.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/composer/
    - assets/audio/
