// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAKxNjZ1Yy6pWZTSSWO-ss6cJOtAIToCY',
    appId: '1:574591046677:web:3f789085d567099fc1aa1c',
    messagingSenderId: '574591046677',
    projectId: 'sleep-sounds-1e708',
    authDomain: 'sleep-sounds-1e708.firebaseapp.com',
    storageBucket: 'sleep-sounds-1e708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZnHEXBrDlFCzQ8Gs1kQiDc1ESxKbke-U',
    appId: '1:574591046677:android:f0c0e74e29cdba4cc1aa1c',
    messagingSenderId: '574591046677',
    projectId: 'sleep-sounds-1e708',
    storageBucket: 'sleep-sounds-1e708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD58gneU79CZuzSuvjOy_naAk2WMPVS4Ag',
    appId: '1:574591046677:ios:0464c725e39fb6f8c1aa1c',
    messagingSenderId: '574591046677',
    projectId: 'sleep-sounds-1e708',
    storageBucket: 'sleep-sounds-1e708.appspot.com',
    iosBundleId: 'com.example.flutterSleepSounds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD58gneU79CZuzSuvjOy_naAk2WMPVS4Ag',
    appId: '1:574591046677:ios:0b2814cb86ad1bb9c1aa1c',
    messagingSenderId: '574591046677',
    projectId: 'sleep-sounds-1e708',
    storageBucket: 'sleep-sounds-1e708.appspot.com',
    iosBundleId: 'com.example.flutterSleepSounds.RunnerTests',
  );
}
